# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    def forwards_func(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        db_alias = schema_editor.connection.alias
        # Create default province
        Province = apps.get_model("profiles", "Province")
        Province.objects.using(db_alias).bulk_create([
            Province(code="DO-01", name="Santo Domingo, DN"),
        ])

        province = Province.objects.using(db_alias).get(code="DO-01")

        # Create sectors for Province
        Sector = apps.get_model("profiles", "Sector")
        province.sector_set.using(db_alias).bulk_create([
            Sector(code="10101", name="Centro de Los Heroes", province=province),
            Sector(code="10102", name="Mata Hambre", province=province),
            Sector(code="10103", name="Zona Universitaria", province=province),
            Sector(code="10104", name="San Geronimo", province=province),
            Sector(code="10105", name="Ciudad Universitaria", province=province),
            Sector(code="10106", name="Los Robles", province=province),
            Sector(code="10107", name="El Vergel", province=province),
            Sector(code="10107", name="Esperilla", province=province),
            Sector(code="10108", name="El Manguito", province=province),
            Sector(code="10109", name="La Julia", province=province),
            Sector(code="10110", name="El Embajador", province=province),
            Sector(code="10111", name="Bella Vista", province=province),
            Sector(code="10113", name="Sarasota", province=province),
            Sector(code="10114", name="Mirador Norte", province=province),
            Sector(code="10115", name="Atala", province=province),
            Sector(code="10115", name="El Portal", province=province),
            Sector(code="10115", name="Rocamar", province=province),
            Sector(code="10116", name="30 de Mayo", province=province),
            Sector(code="10116", name="Ciudad Gandera", province=province),
            Sector(code="10117", name="Ensanche La Paz", province=province),
            Sector(code="10117", name="Hoduras", province=province),
            Sector(code="10118", name="Antillas", province=province),
            Sector(code="10118", name="Costa Brava", province=province),
            Sector(code="10118", name="El Cacique", province=province),
            Sector(code="10118", name="Los Arrecifes", province=province),
            Sector(code="10119", name="Naco", province=province),
            Sector(code="10120", name="La Yuca", province=province),
            Sector(code="10121", name="Arboleda (naco)", province=province),
            Sector(code="10122", name="Centro Olimpico", province=province),
            Sector(code="10125", name="Lopez de Vega", province=province),
            Sector(code="10126", name="Paraiso", province=province),
            Sector(code="10127", name="Piantini", province=province),
            Sector(code="10128", name="Carmelita", province=province),
            Sector(code="10129", name="Urbanización Fernandez", province=province),
            Sector(code="10130", name="Julieta Morales", province=province),
            Sector(code="10130", name="Los Praditos", province=province),
            Sector(code="10131", name="Los Prados", province=province),
            Sector(code="10133", name="Castellana", province=province),
            Sector(code="10135", name="Ciudad Moderna", province=province),
            Sector(code="10135", name="Encarnacion", province=province),
            Sector(code="10135", name="Urbanización Las Praderas", province=province),
            Sector(code="10136", name="Residencial Rosmil", province=province),
            Sector(code="10137", name="Los Restauradores", province=province),
            Sector(code="10138", name="Manganagua", province=province),
            Sector(code="10139", name="Los Millones", province=province),
            Sector(code="10143", name="Estela Marina (los Millones)", province=province),
            Sector(code="10145", name="Ensanche Quisqueya", province=province),
            Sector(code="10147", name="Evaristo Morales", province=province),
            Sector(code="10149", name="El Millon", province=province),
            Sector(code="10201", name="Don Bosco", province=province),
            Sector(code="10203", name="Miraflores", province=province),
            Sector(code="10204", name="Gazcue (plaza de La Cultura)", province=province),
            Sector(code="10205", name="Gazcue", province=province),
            Sector(code="10206", name="Ensanche Independencia", province=province),
            Sector(code="10207", name="La Primavera", province=province),
            Sector(code="10208", name="Ciudad Nueva", province=province),
            Sector(code="10209", name="Ensanche Lugo", province=province),
            Sector(code="10210", name="Zona Colonial", province=province),
            Sector(code="10211", name="San Lazaro", province=province),
            Sector(code="10212", name="San Miguel", province=province),
            Sector(code="10213", name="Borojol", province=province),
            Sector(code="10214", name="Villa Francisca", active=False, province=province),
            Sector(code="10216", name="San Carlos", active=False, province=province),
            Sector(code="10218", name="Reparto Aguedita (gazcue)", province=province),
            Sector(code="10301", name="Mejoramiento Social", province=province),
            Sector(code="10302", name="Guachupita", active=False, province=province),
            Sector(code="10302", name="La Fuente", province=province),
            Sector(code="10302", name="Maria Auxiliadora", province=province),
            Sector(code="10302", name="San Martin de Porres", province=province),
            Sector(code="10303", name="La Cienaga", active=False, province=province),
            Sector(code="10304", name="Domingo Savio", province=province),
            Sector(code="10304", name="Los Guandules", active=False, province=province),
            Sector(code="10305", name="27 de Febrero", active=False, province=province),
            Sector(code="10305", name="Agua Dulce", province=province),
            Sector(code="10307", name="Villa Maria", active=False, province=province),
            Sector(code="10308", name="Villa Consuelo", active=False, province=province),
            Sector(code="10401", name="Ensanche Luperon", active=False, province=province),
            Sector(code="10402", name="Ensanche Espaillat", active=False, province=province),
            Sector(code="10403", name="Gualey", active=False, province=province),
            Sector(code="10404", name="24 de Abril", province=province),
            Sector(code="10405", name="Simon Bolivar", active=False, province=province),
            Sector(code="10407", name="Capotillo", active=False, province=province),
            Sector(code="10408", name="La Zurza", active=False, province=province),
            Sector(code="10409", name="Villas Agricolas", active=False, province=province),
            Sector(code="10410", name="La Caridad", province=province),
            Sector(code="10411", name="El Ensanchito", province=province),
            Sector(code="10412", name="Villa Juana", active=False, province=province),
            Sector(code="10501", name="Cristo Rey", active=False, province=province),
            Sector(code="10501", name="El Caliche", active=False, province=province),
            Sector(code="10501", name="Trueva", province=province),
            Sector(code="10502", name="La Cuarenta", active=False, province=province),
            Sector(code="10502", name="Las Flores", province=province),
            Sector(code="10502", name="Santa Rosa", province=province),
            Sector(code="10502", name="Yaquito", province=province),
            Sector(code="10503", name="La Isabela", province=province),
            Sector(code="10503", name="Parque Isabela", province=province),
            Sector(code="10504", name="Cerros de Arroyo Hondo", province=province),
            Sector(code="10504", name="Cuesta Hermosa III", province=province),
            Sector(code="10504", name="Isabel Villas", province=province),
            Sector(code="10505", name="Arroyo Manzano", province=province),
            Sector(code="10505", name="Buena Vista", province=province),
            Sector(code="10505", name="Cuesta Brava", province=province),
            Sector(code="10505", name="Fundacion", province=province),
            Sector(code="10505", name="La Meseta", province=province),
            Sector(code="10505", name="Manzano", province=province),
            Sector(code="10505", name="Pista de Motocros La Yuca", province=province),
            Sector(code="10505", name="Urbanización Puerta de Hierro", province=province),
            Sector(code="10506", name="Altos de Arroyo Hondo II", province=province),
            Sector(code="10507", name="Colinas de Arroyo Hondo", province=province),
            Sector(code="10507", name="Cuesta Hermosa", province=province),
            Sector(code="10507", name="La Puya", province=province),
            Sector(code="10507", name="Lomas de Arroyo Hondo", province=province),
            Sector(code="10507", name="Los Arroyos", province=province),
            Sector(code="10508", name="El Pino", province=province),
            Sector(code="10508", name="La Aldaba", province=province),
            Sector(code="10508", name="Los Pinos", province=province),
            Sector(code="10509", name="Carmen Amelia", province=province),
            Sector(code="10509", name="La Agustinita", province=province),
            Sector(code="10510", name="Los Caminos", province=province),
            Sector(code="10510", name="Viejo Arroyo Hondo", province=province),
            Sector(code="10511", name="La Fe", province=province),
            Sector(code="10513", name="Ensanche Kennedy", province=province),
            Sector(code="10514", name="Cachiman", province=province),
            Sector(code="10514", name="Ensanche La Fe", province=province),
            Sector(code="10515", name="Barrio Obrero", province=province),
            Sector(code="10516", name="La Agustina", province=province),
            Sector(code="10516", name="La Cementera", province=province),
            Sector(code="10516", name="Lanna Gautier", province=province),
            Sector(code="10601", name="Constelacion", province=province),
            Sector(code="10601", name="Los Proceres", province=province),
            Sector(code="10602", name="Los Jardines del Norte", province=province),
            Sector(code="10603", name="Las Villas", province=province),
            Sector(code="10604", name="La Esperanza", province=province),
            Sector(code="10604", name="Los Rios", province=province),
            Sector(code="10605", name="Altos de Arroyo Hondo I", province=province),
            Sector(code="10605", name="Altos de Arroyo Hondo III", province=province),
            Sector(code="10605", name="Cerros de Arroyo Hondo III", province=province),
            Sector(code="10606", name="Colinas del Seminario", province=province),
            Sector(code="10606", name="Residencial La Yuca", province=province),
            Sector(code="10607", name="Don Honorio", province=province),
            Sector(code="10607", name="El Condado", province=province),
            Sector(code="10607", name="La Ceiba", province=province),
            Sector(code="10607", name="Los Guayabos", province=province),
            Sector(code="10607", name="Villa Claudia", province=province),
            Sector(code="10608", name="Las Colinas", province=province),
            Sector(code="10608", name="Pradera Hermosa", province=province),
            Sector(code="10608", name="Villa Elena", province=province),
            Sector(code="10608", name="Villa Marina", province=province),
        ])

    def reverse_func(apps, schema_editor):
        # forwards_func() creates two Country instances,
        # so reverse_func() should delete them.
        Sector = apps.get_model("profiles", "Sector")
        Province = apps.get_model("profiles", "Province")
        db_alias = schema_editor.connection.alias
        Sector.objects.using(db_alias).all().delete()
        Province.objects.using(db_alias).all().delete()

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Province')),
            ],
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
