# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 23:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170906_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profiles.Sector',
                                    null=True),
            preserve_default=False,
        ),
    ]
