# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170926_2018'),
    ]

    def forwards_func(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        db_alias = schema_editor.connection.alias
        # Create Santo Domingo province
        Province = apps.get_model("profiles", "Province")
        Province.objects.using(db_alias).bulk_create([
            Province(code="DO-32", name="Santo Domingo"),
        ])
        santo_domingo = Province.objects.using(db_alias).get(code="DO-32")

        # Create Santo Domingo Este Municipality
        Municipality = apps.get_model("profiles", "Municipality")
        santo_domingo.municipality_set.using(db_alias).bulk_create([
            Municipality(name="Santo Domingo Este", province=santo_domingo),
        ])

        santo_domingo_este = Municipality.objects.using(db_alias).get(name="Santo Domingo Este")

        # Create sectors for Santo Domingo Este
        Sector = apps.get_model("profiles", "Sector")
        santo_domingo_este.sector_set.using(db_alias).bulk_create([
            Sector(code="11501", name="Ensanche Ozama", municipality=santo_domingo_este, active=True),
            Sector(code="11502", name="Molinuevo", municipality=santo_domingo_este, active=False),
            Sector(code="11503", name="Ensanche Alma Rosa (lado Oeste)", municipality=santo_domingo_este, active=True),
            Sector(code="11503", name="Jardines de Alma Rosa", municipality=santo_domingo_este, active=True),
            Sector(code="11504", name="Ensanche Alma Rosa (lado Este)", municipality=santo_domingo_este, active=True),
            Sector(code="11505", name="Villa Faro", municipality=santo_domingo_este, active=False),
            Sector(code="11506", name="Alma Rosa II", municipality=santo_domingo_este, active=True),
            Sector(code="11506", name="El Rosal", municipality=santo_domingo_este, active=False),
            Sector(code="11506", name="Ivette", municipality=santo_domingo_este, active=False),
            Sector(code="11506", name="Urbanización Italia", municipality=santo_domingo_este, active=True),
            Sector(code="11507", name="Ralma", municipality=santo_domingo_este, active=False),
            Sector(code="11507", name="Savica", municipality=santo_domingo_este, active=False),
            Sector(code="11508", name="Franconia", municipality=santo_domingo_este, active=False),
            Sector(code="11508", name="La Esperanza", municipality=santo_domingo_este, active=False),
            Sector(code="11508", name="Loteria", municipality=santo_domingo_este, active=False),
            Sector(code="11508", name="Paraiso Oriental", municipality=santo_domingo_este, active=False),
            Sector(code="11508", name="Urbanización Amanda", municipality=santo_domingo_este, active=False),
            Sector(code="11508", name="Vecinos Unidos", municipality=santo_domingo_este, active=False),
            Sector(code="11509", name="Alpes I", municipality=santo_domingo_este, active=False),
            Sector(code="11509", name="Bello Campo", municipality=santo_domingo_este, active=False),
            Sector(code="11509", name="Hamarap", municipality=santo_domingo_este, active=False),
            Sector(code="11509", name="Isabel", municipality=santo_domingo_este, active=False),
            Sector(code="11509", name="Mi Sueño", municipality=santo_domingo_este, active=False),
            Sector(code="11509", name="Residencial Oriente", municipality=santo_domingo_este, active=False),
            Sector(code="11509", name="Sol Naciente", municipality=santo_domingo_este, active=True),
            Sector(code="11510", name="Carolina", municipality=santo_domingo_este, active=False),
            Sector(code="11510", name="El Brisal", municipality=santo_domingo_este, active=False),
            Sector(code="11510", name="Mendoza", municipality=santo_domingo_este, active=False),
            Sector(code="11510", name="Mi Hogar", municipality=santo_domingo_este, active=False),
            Sector(code="11510", name="Residencial del Este", municipality=santo_domingo_este, active=False),
            Sector(code="11511", name="Las Palmas", municipality=santo_domingo_este, active=False),
            Sector(code="11511", name="Reparto Alma Rosa", municipality=santo_domingo_este, active=False),
            Sector(code="11512", name="Cancino I", municipality=santo_domingo_este, active=False),
            Sector(code="11512", name="Cancino II", municipality=santo_domingo_este, active=False),
            Sector(code="11512", name="Duarte", municipality=santo_domingo_este, active=False),
            Sector(code="11512", name="Los Trinitarios", municipality=santo_domingo_este, active=False),
            Sector(code="11512", name="Mandinga", municipality=santo_domingo_este, active=False),
            Sector(code="11512", name="Narcisa", municipality=santo_domingo_este, active=False),
            Sector(code="11513", name="Cabirma del Este I", municipality=santo_domingo_este, active=False),
            Sector(code="11513", name="Residencial Lomisa", municipality=santo_domingo_este, active=False),
            Sector(code="11514", name="Residencial Idalia A I", municipality=santo_domingo_este, active=False),
            Sector(code="11515", name="El Cachon", municipality=santo_domingo_este, active=False),
            Sector(code="11515", name="Prados del Cachon", municipality=santo_domingo_este, active=False),
            Sector(code="11516", name="Cancino", municipality=santo_domingo_este, active=False),
            Sector(code="11516", name="Lucerna", municipality=santo_domingo_este, active=False),
            Sector(code="11517", name="Cancino Adentro", municipality=santo_domingo_este, active=False),
            Sector(code="11517", name="Colinas del Este", municipality=santo_domingo_este, active=False),
            Sector(code="11517", name="El Cachon de La Rubia", municipality=santo_domingo_este, active=False),
            Sector(code="11809", name="Residencial Don Oscar", municipality=santo_domingo_este, active=False),
            Sector(code="11517", name="Vista Hermosa", municipality=santo_domingo_este, active=False),
            Sector(code="11518", name="Residencial Amapola", municipality=santo_domingo_este, active=False),
            Sector(code="11518", name="San Pablo II", municipality=santo_domingo_este, active=False),
            Sector(code="11519", name="Altos de Cancino", municipality=santo_domingo_este, active=False),
            Sector(code="11601", name="Calero", municipality=santo_domingo_este, active=False),
            Sector(code="11601", name="Pueblo Nuevo", municipality=santo_domingo_este, active=False),
            Sector(code="11602", name="La Francia", municipality=santo_domingo_este, active=False),
            Sector(code="11602", name="Simonico", municipality=santo_domingo_este, active=False),
            Sector(code="11602", name="Villa Duarte", municipality=santo_domingo_este, active=False),
            Sector(code="11801", name="Los Molinos", municipality=santo_domingo_este, active=False),
            Sector(code="11603", name="Parque del Este I", municipality=santo_domingo_este, active=False),
            Sector(code="11603", name="San Souci", municipality=santo_domingo_este, active=False),
            Sector(code="11604", name="Faro A Colon", municipality=santo_domingo_este, active=False),
            Sector(code="11604", name="Maquiteria", municipality=santo_domingo_este, active=False),
            Sector(code="11604", name="Parque Mirador Este", municipality=santo_domingo_este, active=False),
            Sector(code="11604", name="Residencial Parque del Este", municipality=santo_domingo_este, active=False),
            Sector(code="11605", name="Los Tres Ojos", municipality=santo_domingo_este, active=True),
            Sector(code="11606", name="Las Americas", municipality=santo_domingo_este, active=False),
            Sector(code="11606", name="Villa Olimpica", municipality=santo_domingo_este, active=False),
            Sector(code="11704", name="Corales del Sur", municipality=santo_domingo_este, active=True),
            Sector(code="11704", name="Residencial Teresa", municipality=santo_domingo_este, active=False),
            Sector(code="11704", name="Tropical del Este", municipality=santo_domingo_este, active=False),
            Sector(code="11705", name="Arismar", municipality=santo_domingo_este, active=False),
            Sector(code="11705", name="Los Frailes", municipality=santo_domingo_este, active=True),
            Sector(code="11705", name="Marbella III", municipality=santo_domingo_este, active=False),
            Sector(code="11706", name="Los Frailes II", municipality=santo_domingo_este, active=False),
            Sector(code="11706", name="Reparto Caribe", municipality=santo_domingo_este, active=False),
            Sector(code="11706", name="San Bartolo", municipality=santo_domingo_este, active=False),
            Sector(code="11707", name="Lotificacion del Este", municipality=santo_domingo_este, active=False),
            Sector(code="11707", name="Villa Adela", municipality=santo_domingo_este, active=False),
            Sector(code="11707", name="Villa Eloisa", municipality=santo_domingo_este, active=False),
            Sector(code="11708", name="Mirador Este", municipality=santo_domingo_este, active=False),
            Sector(code="11801", name="Ana Virginia", municipality=santo_domingo_este, active=False),
            Sector(code="11801", name="Issfapol", municipality=santo_domingo_este, active=False),
            Sector(code="11801", name="Los Trinitarios II", municipality=santo_domingo_este, active=False),
            Sector(code="11802", name="Ciudad de Los Trabajadores", municipality=santo_domingo_este, active=False),
            Sector(code="11802", name="Eugenio María de Hostos", municipality=santo_domingo_este, active=False),
            Sector(code="11802", name="Invivienda", municipality=santo_domingo_este, active=False),
            Sector(code="11802", name="Reparto Villa Carmen", municipality=santo_domingo_este, active=False),
            Sector(code="11802", name="Trabajadores", municipality=santo_domingo_este, active=False),
            Sector(code="11802", name="Villa Carmen", municipality=santo_domingo_este, active=False),
            Sector(code="11803", name="Barrio Brisa de Charles", municipality=santo_domingo_este, active=False),
            Sector(code="11803", name="Brisa del Eden", municipality=santo_domingo_este, active=False),
            Sector(code="11803", name="Residencial Clarimar", municipality=santo_domingo_este, active=False),
            Sector(code="11803", name="San Jose de Mendoza", municipality=santo_domingo_este, active=False),
            Sector(code="11804", name="Amarilis III", municipality=santo_domingo_este, active=False),
            Sector(code="11804", name="Nuevo Amanecer", municipality=santo_domingo_este, active=False),
            Sector(code="11804", name="Residencial Fernandez Oriental", municipality=santo_domingo_este, active=False),
            Sector(code="11804", name="Residencial Mirador del Este", municipality=santo_domingo_este, active=False),
            Sector(code="11805", name="Barrio John F. Kennedy", municipality=santo_domingo_este, active=False),
            Sector(code="11805", name="Buena Ventura II", municipality=santo_domingo_este, active=False),
            Sector(code="11805", name="Los Restauradores", municipality=santo_domingo_este, active=False),
            Sector(code="11805", name="Villa Esfuerzo", municipality=santo_domingo_este, active=False),
            Sector(code="11806", name="Ciudad del Almirante I", municipality=santo_domingo_este, active=False),
            Sector(code="11806", name="Ciudad del Almirante II", municipality=santo_domingo_este, active=False),
            Sector(code="11806", name="Zona Franca Industrial de Herrera", municipality=santo_domingo_este,
                   active=False),
            Sector(code="11807", name="Hainamosa", municipality=santo_domingo_este, active=False),
            Sector(code="11807", name="Invi Cea", municipality=santo_domingo_este, active=False),
            Sector(code="11807", name="Invimosa", municipality=santo_domingo_este, active=False),
            Sector(code="11807", name="Los Pinos", municipality=santo_domingo_este, active=False),
            Sector(code="11807", name="Nuevo Renacer", municipality=santo_domingo_este, active=False),
            Sector(code="11807", name="Parque Industrial Nueva Isabela", municipality=santo_domingo_este, active=False),
            Sector(code="11807", name="Urbanización Ana Teresa Balaguer", municipality=santo_domingo_este,
                   active=False),
            Sector(code="11808", name="Batey La Balsa", municipality=santo_domingo_este, active=False),
            Sector(code="11808", name="Batey Piragua", municipality=santo_domingo_este, active=False),
            Sector(code="11808", name="Sabaneta", municipality=santo_domingo_este, active=False),
            Sector(code="11809", name="Barrio Paraiso", municipality=santo_domingo_este, active=False),
            Sector(code="11809", name="Cabirma del Este II", municipality=santo_domingo_este, active=False),
            Sector(code="11809", name="El Tamarindo", municipality=santo_domingo_este, active=False),
            Sector(code="11809", name="Los Rosales", municipality=santo_domingo_este, active=False),
            Sector(code="11901", name="La Milagrosa", municipality=santo_domingo_este, active=False),
            Sector(code="11901", name="Los Mina Sur", municipality=santo_domingo_este, active=False),
            Sector(code="11901", name="Pidoca", municipality=santo_domingo_este, active=False),
            Sector(code="11902", name="Felicidad", municipality=santo_domingo_este, active=False),
            Sector(code="11902", name="San Antonio", municipality=santo_domingo_este, active=False),
            Sector(code="11902", name="Vietnan", municipality=santo_domingo_este, active=False),
            Sector(code="11903", name="Katanga", municipality=santo_domingo_este, active=False),
            Sector(code="11903", name="Los Mina Norte", municipality=santo_domingo_este, active=False),
            Sector(code="11904", name="Cerros del Ozama", municipality=santo_domingo_este, active=False),
            Sector(code="11904", name="Francisco Del", municipality=santo_domingo_este, active=False),
            Sector(code="11904", name="Las Frutas", municipality=santo_domingo_este, active=False),
            Sector(code="11904", name="Puerto Rico", municipality=santo_domingo_este, active=False),
            Sector(code="11904", name="Rosario Sanchez", municipality=santo_domingo_este, active=False),
            Sector(code="11905", name="Los 3 Brazos", municipality=santo_domingo_este, active=False),
            Sector(code="11905", name="Mil Flores", municipality=santo_domingo_este, active=False),
            Sector(code="11906", name="Las Enfermeras", municipality=santo_domingo_este, active=False),
            Sector(code="11906", name="Los Mina Viejo", municipality=santo_domingo_este, active=False),
        ])

    def reverse_func(apps, schema_editor):
        # forwards_func() creates two Country instances,
        # so reverse_func() should delete them.
        Sector = apps.get_model("profiles", "Sector")
        Municipality = apps.get_model("profiles", "Municipality")
        Province = apps.get_model("profiles", "Province")
        db_alias = schema_editor.connection.alias
        province = Province.objects.using(db_alias).get(code='DO-32')
        santo_domingo_este = Municipality.objects.using(db_alias).get(province=province)
        santo_domingo_este.sector_set.delete()
        santo_domingo_este.delete()
        province.delete()

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]

