# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20170930_1047'),
    ]

    def forwards_func(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        db_alias = schema_editor.connection.alias
        # Create Santo Domingo province
        Province = apps.get_model("profiles", "Province")
        distrito_nacional = Province.objects.using(db_alias).get(code="DO-01")

        # Create Santo Domingo Oeste Municipality
        """
        Municipality = apps.get_model("profiles", "Municipality")

        santo_domingo.municipality_set.using(db_alias).bulk_create([
            Municipality(name="Santo Domingo Oeste", province=santo_domingo),
        ])

        santo_domingo_oeste = Municipality.objects.using(db_alias).get(name="Santo Domingo Oeste")"""

        # Add sectors for Santo Domingo
        Sector = apps.get_model("profiles", "Sector")
        Sector.objects.using(db_alias).bulk_create([
            Sector(code="0000", name="Invi nuevo - Gacela KM. 9½", province=distrito_nacional, active=True),
            Sector(code="0000", name="Buenos aires del mirador KM. 9", province=distrito_nacional, active=True),
            Sector(code="0000", name="José contreras - Pedregal (KM. 10½)", province=distrito_nacional, active=True),
            Sector(code="0000", name="Pradera verde (KMs. 11-12)", province=distrito_nacional, active=True),
            Sector(code="0000", name="Enriquillo, San Miguel, Lotería (KMs. 7½-9½)", province=distrito_nacional, active=True),
            Sector(code="0000", name="Jordines del Sur - Las acacias (KMs. 7-7½)", province=distrito_nacional, active=True),
            Sector(code="0000", name="Tropical Metaldom - Dominicanos Ausentes (KMs. 6-7)", province=distrito_nacional, active=True),
            Sector(code="0000", name="Mar Azul, Miramar, Nordesa (KMs. 7-8½)", province=distrito_nacional, active=True),
            Sector(code="0000", name="Costa Caribe, Velas casas, Aesa, Mar Caribe (KMs. 9-12)", province=distrito_nacional, active=True),
        ])
        sector_obj = Sector.objects.using(db_alias)
        sector_obj.filter(code="10116", province=distrito_nacional, name__icontains="30 de mayo").update(name="30 de Mayo (Cervecería)")
        sector_obj.filter(code="10143", province=distrito_nacional).update(name="Estela Maria (El Millon)")

    def reverse_func(apps, schema_editor):
        # forwards_func() creates two Country instances,
        # so reverse_func() should delete them.
        # TODO: Delete also new sectors added by ID.
        Sector = apps.get_model("profiles", "Sector")
        Province = apps.get_model("profiles", "Province")
        db_alias = schema_editor.connection.alias
        distrito_nacional = Province.objects.using(db_alias).get(code='DO-01')
        sector_obj = Sector.objects.using(db_alias)
        sector_obj.filter(code="10116", province=distrito_nacional, name__icontains="30 de mayo").update(name="30 de mayo")
        sector_obj.get(code="10143", province=distrito_nacional, name__icontains="estela marina").update(name="Estela Marina (los Millones)")

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
