# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 03:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20170930_1132'),
    ]

    def forwards_func(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        db_alias = schema_editor.connection.alias
        # Create Santo Domingo province
        Province = apps.get_model("profiles", "Province")
        distrito_nacional = Province.objects.using(db_alias).get(code="DO-01")

        # Create Santo Domingo Oeste Municipality
        """
        Municipality = apps.get_model("profiles", "Municipality")

        santo_domingo.municipality_set.using(db_alias).bulk_create([
            Municipality(name="Santo Domingo Oeste", province=santo_domingo),
        ])

        santo_domingo_oeste = Municipality.objects.using(db_alias).get(name="Santo Domingo Oeste")"""

        # Add sectors for Santo Domingo
        Sector = apps.get_model("profiles", "Sector")
        Sector.objects.using(db_alias).bulk_create([
            Sector(code="0000", name="Custa Hermosa II", province=distrito_nacional, active=True),
            Sector(code="0000", name="El Galá", province=distrito_nacional, active=True),
            Sector(code="0000", name="Ensanche Carmelita", province=distrito_nacional, active=True),
            Sector(code="0000", name="Ensanche Julieta", province=distrito_nacional, active=True),
            Sector(code="0000", name="Gascue", province=distrito_nacional, active=True),
            Sector(code="0000", name="Jardines del Caribe", province=distrito_nacional, active=True),
            Sector(code="0000", name="Jardines del Embajador", province=distrito_nacional, active=True),
            Sector(code="0000", name="La Feria", province=distrito_nacional, active=True),
            Sector(code="0000", name="Los Cacicazgos", province=distrito_nacional, active=True),
            Sector(code="0000", name="Los Jardines", province=distrito_nacional, active=True),
            Sector(code="0000", name="Mirador Norte (Bella Vista)", province=distrito_nacional, active=True),
            Sector(code="0000", name="Mirador Sur", province=distrito_nacional, active=True),
            Sector(code="0000", name="Renacimiento", province=distrito_nacional, active=True),
            Sector(code="0000", name="Serrallés", province=distrito_nacional, active=True),
            Sector(code="0000", name="Urbanización Real", province=distrito_nacional, active=True),
        ])
        sector_obj = Sector.objects.using(db_alias)
        sector_obj.filter(code="10505", province=distrito_nacional, name__icontains="Puerta de hierro").update(active=False)

    def reverse_func(apps, schema_editor):
        # forwards_func() creates two Country instances,
        # so reverse_func() should delete them.
        # TODO: Delete also new sectors added by ID.
        Sector = apps.get_model("profiles", "Sector")
        Province = apps.get_model("profiles", "Province")
        db_alias = schema_editor.connection.alias
        distrito_nacional = Province.objects.using(db_alias).get(code='DO-01')
        sector_obj = Sector.objects.using(db_alias)
        sector_obj.filter(code="10505", province=distrito_nacional, name__icontains="Puerta de hierro").update(active=True)

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]

