language: python
python:
- 3.6
env:
- DJANGO_SETTINGS_MODULE=blutickets.settings.test
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: heroku
  app:
    master: prod-blutickets
    dev: dev-blutickets
  api_key:
    secure: f8v56MD/0K2e6dHLo0/msqdqIIdwvcNO/iUHgkx/JI7t9P5TN6mZm/zGLGQx/0NOlX36R46I4YB6R62bzMc716WGPs4aj7YeyW01341aOM4LKQIsO+5Xd4+h76KHzYYpeWm0PCvu8PL6w/P96a8spuPq99iLr5TJgwDCtC6BqhbfgpzP5EFaBL5OTzicJdzcU3BhFQOaE7xkfOR4SNJFCMVyOKBKPFdghJmTCESFD6Blv3nqPVhHlJ8O5+o9fMpNwuRRWuO2lDD1S6xgA3OvZFg2cHYjIb1msqLn/6g6xcWCAaG6FPcKjkebocwGH5ke8SS1LuVSZFrGky51NPmgLZp6AEhVtsvMhhCod3PmBseyg06bjScnqTJGDnTCqK6nCRPvaTGORGkzvYBo8sWySfdmhCBIZTdu+KCCTs/jjsTzaFhobAGIVnchof+C3czgWgQErZOWa/VA3iARY16ZIPlmvLcZ/tXXAAU6eBWfERWD1FblOq73wiQIlCP6rIjSfhNdeB+Kj4y94+rfv5HeLokalFqe/jEjpkwcYJrGJW620nYuC+U8fyq7N20Iw/jjPMk3g/52VqtXUJcq5MyRpOpSlaQhgwk03/0H2UzeLtRUncplIkxR8eutc75tkWetc+YnzFJjge+/vQp6L0ay6s1AIkBOUT+5DE/nAUke6eE=
notifications:
  slack:
    secure: FMLsrq0HfPN/JgNhLFTG8+ThOTuEH13ozayIz3fFnwtQdmOGUbLy1oWRBIqUIn/NgiQ0D/RIP92OVnIncitMV0Mx3sMQZt+CWsPZUZDcYyZzgw0kJXWyMWq1sUB4RVT0uINrzvArQ2VrTZ76viwdEeH/xczffKFmZYg0lL7HAAy1K2XTE6X4a31/rN4SwfyO5vzu/qG+sweFSRdyBufvyc1O3rKRc2ni7QRU6VrdhQZG28ftBJH4UndpEnBRNCwflJl8aN9LBSXVHhtm7cuBKJ0XnaKVhm1S7b0PiKKB9VaiJaZaLfJRvtC10bUG91ZgWUNceN2HA7WosEQmCKo63WLyQz3mkhomKys0ZA8VoOhIKUcavntXOzC8Eqh4A9uvdvc/8pNF9C7AzvXC5GRgZjAcE2wPvJz8aRaTbjZZDItvj4TUP4vn46Lw05aWAXLvy6HLywTfytQUA8ojQANtRDrQvE9ANvInH+JMjUc8rqyT12JSydO9XcSi5NnbAUhpAj/2b3SZQD8Tn/N2JkBZ4brbPRD8qyk95MJEGwUgmJbgvzjDjbgpBHCosSWJf79mTW+zmAaxfaqALs8BrykRbrgfwgCvbSSXdhEzOOGM96kIm4Tqq/3FfkmCMpxD8TiknqAZawOrwUVHye5fIwMr1Sdj2ehESiVmBTGWQ6Nm1h0=
