language: python
cache: pip
python:
- 3.6
env:
- DJANGO_SETTINGS_MODULE=blutickets.settings.test
install:
- pip install flake8
- pip install -r requirements.txt
before_script:
- flake8 . --exclude migrations,node_modules,settings,manage.py,__init__.py --max-line-length=120
  --ignore=E901,E126,E127,E121
script:
- celery -A blutickets worker -l info&
- python manage.py test
services:
- rabbitmq
deploy:
  provider: heroku
  app:
    master: prod-blutickets
    dev: dev-blutickets
    feature-redesign: redesign-blutickets
  api_key:
    secure: ldcLHVDXli/tLLpZYHuO3WL5HEqm3UPbhhcDeC2RBQni4yJtA0upZOexbahkqzXBP7PIUFKYo7tB2/ynI7BwSdjVeGYcH53+NxzmcS/lminUsgM0y+/b//NoA66y1kWDeUGxm4h/D1dFlVLPLiV7vslAKtF20YtBpB0ATChOyvDE9dEpBbHfzvmYPJBkEMH5Iml+XcNK0XH/rxik8MRBWozZiNxr38LJkMSsLxKa4DD2uu307UFPmA7xmMbkKFwu2mFegvawmBo/x8f8+5yhDLu4P/LyngobOHhPrNks5bxB4mC+xCUsHp4o16D3fnZnjcU1uE3WrtPTbE5qPApoWPk3xaXyIvvM+EGQLeEfRilshWW1JvQUtmtolISr1nA3IK5PWcfmG9y579b1oiK0WMnkOguG1MLi9uyIbpCXrEYarFrfnSEkmKYh5le5rtYCdRUtD0v8+Cyd/gL8oooygeEFSNLukxPwcBrON6RLBv113Lg6wE4F1a5BX8tJcS83vET3fDpjf+eMIntIkO3GVC6lEaxdhwmSo5GcO+Wl22YNs5YvRiDphhkw2T1a6RoLrP7Sozs/yHg2wTpdwRdWbBxVKZgVCxb6Obn4dBTbqyhz0JyN39KomwRaCq3wVgVMTVBh2GOZpiePJenRS2wNo/60uAUMApt6Kyh0+zz9GVo=
notifications:
  slack: blutickets:2yPWlEHDWn8TCi0DgT0UhWjH
