language: python
cache: pip
python:
- 3.6
env:
- DJANGO_SETTINGS_MODULE=blutickets.settings.test
install:
- pip install flake8
- pip install -r requirements.txt
before_script:
- flake8 . --exclude migrations,node_modules,settings,manage.py,__init__.py --max-line-length=120
  --ignore=E901,E126,E127,E121
script:
- celery -A blutickets worker -l info&
- python manage.py test
services:
- rabbitmq
deploy:
  provider: heroku
  app:
    master: prod-blutickets
    dev: dev-blutickets
    feature-redesign: redesign-blutickets
  api_key:
    secure: CrzHxgQ6iEd8sAX4F5NyATImJ0HjziVU1GXgpQYxoPkioDUwezMf8mPA3k45QsOzHRKFRuWc6I8i/li+lv0Lu+qRuyvpGdUN2GU33dXFZcxdupklIPLraezRUcshue60NJxbvDPMNELWLpWbmc0hQ2HZYoJCvEoYcetCQlEj4w95qOPgGhMA4h9PMiY3BkiFAOtdXCqzwdEZLOaQpWHXABZHWyMgoWCL9qZBEI4BlZ5xP27i/Vb4i9aMUj6us3/DuFv0ZF8FmLvvKrZHemkA7tbkL/V9qtlJ2hPExJE4wTY3Hy0rH++V3sgu4taxPg4wpw6P8wBhW4e86/nzvmocVqHm03I5XQClyOXxFBH9RebTq9JVJjAPA9+gbxyMCx8o/XJIUSD01td4uHO5BWfO/7kpg+R458Ydc/4unrjcftF+tLH7t2fOu+5n0v0bP6lAxi0UbkalzbYvieeKUtw+8ISy+UqDyhTmfC9zS0s01FY0BQWWbfK569DMl5SKabkn2QRl7zqXkzm8fD3erOMjq5lZDRmXNKaxt8cAJoJndfCyOISQN4lAg9CoMqEvTlLLkraB0CJNZDtMfFxVMOMT73NlHJj8zZd3hfEGydEpF/0E9L/2ztok6UhPKjqlEfR+UlZS9/F5bMji2fBHXudWgoEjxG8ZWmT2NEixUTEVxQM=
notifications:
  slack: blutickets:2yPWlEHDWn8TCi0DgT0UhWjH
