# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='direction',
            new_name='address',
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='when',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 2, 45, 9, 247951, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
