# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20170824_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='map_position',
            field=geoposition.fields.GeopositionField(default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='flyer_image',
            field=models.ImageField(upload_to='flyers'),
        ),
    ]
