# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20170917_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
