# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_auto_20170918_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
