# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(default=tickets.models.random_string),
        ),
    ]
