# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20171113_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
