"""
Django settings for blutickets project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

from .base import *

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SHELL_PLUS = "ipython"

INSTALLED_APPS += ['django_extensions', 'debug_toolbar',]
GEOPOSITION_GOOGLE_MAPS_API_KEY = env('GEOPOSITION_GOOGLE_MAPS_API_KEY')

SALES_SLACK_CHANNEL = env('SALES_SLACK_CHANNEL')
CONTACT_SLACK_CHANNEL = env('CONTACT_SLACK_CHANNEL')

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, '../db.sqlite3'),
    }
}


def show_toolbar(request):
    return True


DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": show_toolbar,
}

MIDDLEWARE += ['debug_toolbar.middleware.DebugToolbarMiddleware']
# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '../staticfiles'),
]
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '../media')

LOCALE_PATHS = [
    os.path.join(BASE_DIR, '../profiles/locale'),
]

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST_USER = "noreplyblutickets@gmail.com"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

