# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
