# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20170901_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparacion'), ('pending', 'En espera'), ('rejected', 'Rechazado'), ('approved', 'Aprovado'), ('closed', 'Cerrado')], default='preparing', max_length=20),
        ),
    ]
