# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:43
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170906_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='map_position',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
    ]
