# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_auto_20170917_1159'),
        ('sales', '0006_auto_20170917_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='ttype',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Type'),
        ),
    ]
